cabal-version:      3.4
name:               pb-ast
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Thomas Marsh
maintainer:         thomas.marsh2@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common common-settings
  default-language: GHC2024
  default-extensions:
    NoImplicitPrelude
    OverloadedStrings
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-patterns

library
  import: common-settings
  hs-source-dirs: src
  exposed-modules:
    PB.Prelude
    PB.AST.BodyStmt
    PB.AST.Expr
    PB.AST.SourceFile
    PB.Grammar.Body
    PB.Grammar.File
    PB.Grammar.Stream
    PB.Lexing.Lexer
    PB.Lexing.Mask
    PB.Lexing.Splitter
    PB.Lexing.Token
    PB.Pipeline.Preprocess
    PB.Pipeline.Runner
    PB.Pipeline.Serialise
  build-depends:
    , base ^>=4.20.2.0
    , text
    , megaparsec
    , aeson
    , containers >=0.6
    , filepath >=1.4

executable pb-runner
  import: common-settings
  hs-source-dirs: app
  main-is: Main.hs
  build-depends:
    , base ^>=4.20.2.0
    , pb-ast
    , text
    , aeson
    , bytestring   ^>=0.12
    , directory    ^>=1.3
    , filepath     >=1.4
    , optparse-applicative ^>=0.18

test-suite pb-ast-test
  import: common-settings
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules: BodyParserTest, BodyStmtTest, CorpusInvariantTest, CorpusTest, ExprTest, FileTest, MaskTest, RunnerTest, SerialiseTest, SplitterTest, StreamTest, TokenTest
  build-depends:
    , base ^>=4.20.2.0
    , pb-ast
    , text
    , tasty
    , tasty-hunit
    , tasty-hedgehog
    , hedgehog       >=1.4
    , megaparsec
    , aeson
    , directory    ^>=1.3
    , filepath     >=1.4
