cabal-version:      3.4
name:               pb-ast
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Thomas Marsh
maintainer:         thomas.marsh2@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common common-settings
  default-language: GHC2024
  default-extensions:
    NoImplicitPrelude
    OverloadedStrings
    DuplicateRecordFields
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-patterns

library
  import: common-settings
  hs-source-dirs: src
  exposed-modules:
    PB.Prelude
    PB.AST.BodyStmt
    PB.AST.DataWindow
    PB.AST.Expr
    PB.AST.SourceFile
    PB.Grammar.Body
    PB.Grammar.DataWindow
    PB.Grammar.File
    PB.Grammar.Stream
    PB.Lexing.DataWindow
    PB.Lexing.Escape
    PB.Lexing.Lexer
    PB.Lexing.Mask
    PB.Lexing.Splitter
    PB.Lexing.Token
    PB.Pipeline.Preprocess
    PB.Pipeline.Runner
    PB.Pipeline.Serialise
    PB.Pipeline.Walk
  build-depends:
    , base ^>=4.20.1.0
    , text
    , megaparsec
    , aeson >=2.0
    , aeson-typescript >=0.6
    , template-haskell >=2.21
    , bytestring  ^>=0.12
    , containers >=0.6
    , directory  ^>=1.3
    , filepath   >=1.4
    , unordered-containers >=0.2

executable pb-runner
  import: common-settings
  hs-source-dirs: app
  main-is: Main.hs
  build-depends:
    , base ^>=4.20.1.0
    , pb-ast
    , text
    , aeson
    , bytestring   ^>=0.12
    , directory    ^>=1.3
    , filepath     >=1.4
    , optparse-applicative >=0.18

test-suite pb-ast-test
  import: common-settings
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules:
      BodyParserTest
    , BodyStmtTest
    , CorpusDebtTest
    , DataWindowTest
    , CorpusInvariantTest
    , CorpusTest
    , ExprTest
    , FileTest
    , MaskTest
    , PipelineTest
    , RunnerTest
    , SerialiseTest
    , SplitterTest
    , StreamTest
    , TokenTest
  build-depends:
    , base ^>=4.20.1.0
    , pb-ast
    , text
    , tasty
    , tasty-hunit
    , tasty-hedgehog
    , hedgehog       >=1.4
    , megaparsec
    , aeson
    , containers   >=0.6
    , directory    ^>=1.3
    , filepath     >=1.4
