"""PB API data loaded from doc/pb2025r2 HTML docs.

Generated by scripts/extract_pb_api.py. Do not edit pb_api.json manually.
"""

from __future__ import annotations

import json
from pathlib import Path

_DATA_PATH = Path(__file__).parent / "pb_api.json"
_data: dict | None = None

# Free functions that share names with class methods in the extractor
# but are genuinely callable without a receiver (e.g. clipboard()).
_MANUAL_FREE_FUNCTIONS: list[str] = [
    "clipboard", "filerename", "posrev",
    "opensheet", "opensheetdocked", "opensheetwithparm",
    "opensheetwithparmasdocument",
    "openuserobject", "openuserobjectwithparm",
    "print", "syntaxfromsql", "classname",
]


def _load() -> dict:
    global _data
    if _data is None:
        _data = json.loads(_DATA_PATH.read_text())
    return _data


def get_free_functions() -> frozenset[str]:
    """All PB free functions (globally callable, no receiver needed)."""
    base = set(_load()["free_functions"])
    base.update(_MANUAL_FREE_FUNCTIONS)
    return frozenset(base)


def get_class_methods() -> dict[str, frozenset[str]]:
    """PB class methods keyed by lowercase class name."""
    raw = _load()["class_methods"]
    return {k: frozenset(v) for k, v in raw.items()}
