"""Pure type resolution and call resolution — no I/O dependencies."""

from __future__ import annotations

import json
from typing import Any, cast

from pb_cli.core.ast_walker import walk_tagged
from pb_cli.core.models import (
    CallRow,
    GlobalVarRow,
    LocalVarRow,
    ProcedureRow,
    ResolvedCallRow,
    ResolvedTypeRow,
)

PRIMITIVES = frozenset({
    "string", "integer", "long", "boolean", "double", "decimal",
    "date", "time", "datetime", "blob", "char", "real", "unsigned",
    "byte", "int",
})

PB_BUILTINS = frozenset({
    "datawindow", "datastore", "datawindowchild", "window",
    "pointer", "transaction", "dynamicdescriptionarea",
    "error", "message", "powerobject", "structure",
    "treeviewitem", "dwitemstatus", "menu",
})

# Loaded from pb_cli/data/pb_api.json (generated by scripts/extract_pb_api.py).
from pb_cli.data import (  # noqa: E402
    get_class_method_sigs,
    get_class_methods,
    get_free_function_sigs,
    get_free_functions,
)

PB_BUILTIN_CALLS = get_free_functions()
PB_CLASS_METHODS = get_class_methods()

# Return-type lookups keyed by lowercase name.
_FREE_RETURN: dict[str, str] = {
    fn: sigs[0]["return_type"]
    for fn, sigs in get_free_function_sigs().items()
    if sigs and sigs[0].get("return_type")
}
# Flat method→return_type across all classes (first class that defines the method wins).
_METHOD_RETURN: dict[str, str] = {}
for _cls_methods in get_class_method_sigs().values():
    for _mname, _msigs in _cls_methods.items():
        if _mname not in _METHOD_RETURN and _msigs and _msigs[0].get("return_type"):
            _METHOD_RETURN[_mname] = _msigs[0]["return_type"]


# Naming-convention map for window control type inference (Plan 90a).
# Prefix → PB class name. Longer prefixes first to avoid false matches.
CONTROL_PREFIX_MAP: list[tuple[str, str]] = [
    ("ddplb_", "dropdownpicturelistbox"),
    ("ddlb_", "dropdownlistbox"),
    ("dddw_", "datawindowchild"),
    ("dw_", "datawindow"),
    ("cbx_", "checkbox"),
    ("hpb_", "hprogressbar"),
    ("htb_", "htrackbar"),
    ("hsb_", "hscrollbar"),
    ("vpb_", "vprogressbar"),
    ("vtb_", "vtrackbar"),
    ("vsb_", "vscrollbar"),
    ("plb_", "picturelistbox"),
    ("sh_", "statichyperlink"),
    ("ph_", "picturehyperlink"),
    ("rb_", "radiobutton"),
    ("cb_", "commandbutton"),
    ("st_", "statictext"),
    ("sle_", "singlelineedit"),
    ("mle_", "multilineedit"),
    ("em_", "editmask"),
    ("lb_", "listbox"),
    ("tv_", "treeview"),
    ("lv_", "listview"),
    ("rte_", "richtextedit"),
    ("tab_", "tab"),
    ("gr_", "graph"),
    ("ole_", "olecontrol"),
    ("uo_", "userobject"),
    ("gb_", "groupbox"),
    ("p_", "picture"),
    ("m_", "menu"),
]


def infer_control_type(control_name: str) -> str | None:
    """Infer PB control type from naming convention (e.g. dw_main → datawindow)."""
    lower = control_name.lower()
    for prefix, pb_type in CONTROL_PREFIX_MAP:
        if lower.startswith(prefix):
            return pb_type
    return None


def _resolve_pb_class_from_ancestor(
    obj_name: str,
    objects_table: dict[str, str | None],
) -> str | None:
    """Walk objects.ancestor chain to find the PB built-in class for obj_name.

    Returns the PB class name (e.g. 'window', 'userobject') or None.
    """
    cur = obj_name
    visited: set[str] = set()
    while cur and cur not in visited:
        visited.add(cur)
        ancestor = objects_table.get(cur)
        if ancestor is None:
            return None
        if ancestor.lower() in PB_CLASS_METHODS:
            return ancestor
        cur = ancestor
    return None


def parse_params(params_text: str) -> list[tuple[str, str]]:
    """Parse ``"ref datawindow adw , long row"`` into ``[("adw", "datawindow"), ...]``."""
    if not params_text or not params_text.strip():
        return []
    result: list[tuple[str, str]] = []
    for segment in params_text.split(","):
        segment = segment.strip()
        if not segment:
            continue
        parts = segment.rsplit(None, 1)
        if len(parts) == 2:
            _mods_type, name = parts
            type_words = _mods_type.split()
            if type_words:
                ptype = type_words[-1]
                result.append((name, ptype))
    return result


def classify_type(
    var_type: str,
    objects: set[str],
    user_types: set[str],
) -> tuple[str, str | None]:
    """Return ``(resolved_kind, resolved_target)`` for a declared type string."""
    lower = var_type.lower()
    if lower in PRIMITIVES:
        return ("primitive", None)
    if lower == "any":
        return ("any", None)
    if var_type in objects:
        return ("object", var_type)
    if var_type in user_types:
        return ("user_type", var_type)
    if lower in PB_BUILTINS:
        return ("primitive", None)
    return ("unresolved", None)


def _extract_line(body: list | str, callee_name: str, call_type: str) -> int | None:
    """Walk body_json to find source line for a specific call."""
    if isinstance(body, str):
        body = json.loads(body) if body else []
    for tag, node, line in walk_tagged(body):
        n = cast(dict[str, Any], node)
        if tag == call_type:
            if call_type == "ExCall":
                segs = n.get("callee", {}).get("segments", [])
                if segs:
                    full_name = ".".join(s.get("name", "") for s in segs)
                    if full_name == callee_name:
                        return line
            elif call_type == "ExMethodCall":
                if n.get("method", "") == callee_name:
                    return line
        elif tag == "ExDispatch":
            name = n.get("contents", {}).get("name", "") or n.get("name", "")
            if name == callee_name:
                return line
    return None


def _build_ancestors(
    obj_name: str,
    inherits: dict[str, str],
) -> list[str]:
    """Walk inherits chain from obj_name upward. Returns [obj_name, parent, grandparent, ...]."""
    chain = [obj_name]
    current = obj_name
    visited = {current}
    while current in inherits:
        parent = inherits[current]
        if parent in visited:
            break
        visited.add(parent)
        chain.append(parent)
        current = parent
    return chain


def _resolve_virtual(
    to_name: str,
    obj_name: str,
    proc_map: dict[str, set[str]],
    inherits: dict[str, str],
    global_procs: set[str],
) -> tuple[str | None, str | None, str, str]:
    """Resolve a simple (non-dotted) call via own procedures + ancestor chain + globals.

    Returns (target_object, target_proc, resolution_kind, confidence).
    """
    chain = _build_ancestors(obj_name, inherits)
    found_in: list[str] = []
    for ancestor in chain:
        if to_name in proc_map.get(ancestor, set()):
            found_in.append(ancestor)
    if found_in:
        kind = "inherited" if found_in[0] != obj_name else "virtual"
        return (found_in[0], to_name, kind, "high")
    if to_name in global_procs:
        for obj, procs in proc_map.items():
            if to_name in procs:
                return (obj, to_name, "virtual", "high")
    return (None, None, "unresolved", "low")


def resolve_types(
    local_vars: list[LocalVarRow],
    procedures: list[ProcedureRow],
    objects: set[str],
    user_types: set[str],
) -> list[ResolvedTypeRow]:
    """Build resolved_types from local_variables + parsed procedure params."""
    results: list[ResolvedTypeRow] = []
    for row in local_vars:
        kind, target = classify_type(row.var_type, objects, user_types)
        results.append(ResolvedTypeRow(
            file=row.file, object=row.object, proc_name=row.proc_name,
            var_name=row.var_name, raw_type=row.var_type,
            resolved_kind=kind, resolved_target=target,
            is_parameter=False, scope_line=row.start_line,
        ))

    for proc in procedures:
        if not proc.params:
            continue
        parsed = parse_params(proc.params)
        for name, ptype in parsed:
            kind, target = classify_type(ptype, objects, user_types)
            results.append(ResolvedTypeRow(
                file=proc.file, object=proc.object, proc_name=proc.name,
                var_name=name, raw_type=ptype,
                resolved_kind=kind, resolved_target=target,
                is_parameter=True, scope_line=proc.start_line,
            ))

    return results


def resolve_calls(
    calls: list[CallRow],
    procedures: list[ProcedureRow],
    inherits_rows: list[tuple[str, str]],
    all_objects: set[str] | None = None,
    var_types: dict[tuple[str, str, str], str] | None = None,
    objects_table: dict[str, str | None] | None = None,
) -> list[ResolvedCallRow]:
    """Build resolved_calls from calls + body_json line extraction + resolution.

    var_types maps (object, proc_name, var_name) → resolved type name,
    used to resolve bare calls as methods on typed local variables.

    objects_table maps object name → ancestor (from objects.ancestor column),
    used to walk the inheritance chain to PB built-in classes.
    """
    inherits = dict(inherits_rows)
    proc_map: dict[str, set[str]] = {}
    proc_by_key: dict[tuple[str, str], ProcedureRow] = {}
    for proc in procedures:
        proc_map.setdefault(proc.object, set()).add(proc.name)
        proc_by_key[(proc.object, proc.name)] = proc

    global_procs: set[str] = set()
    for obj, procs in proc_map.items():
        for p in procs:
            global_procs.add(p)

    obj_set = all_objects if all_objects is not None else {proc.object for proc in procedures}
    obj_tbl = objects_table if objects_table is not None else {}

    # Build object → ancestor chain for PB class method resolution
    obj_ancestors: dict[str, list[str]] = {}
    for child, parent in inherits_rows:
        chain = [child]
        cur = child
        visited = {cur}
        while cur in inherits:
            p = inherits[cur]
            if p in visited:
                break
            visited.add(p)
            chain.append(p)
            cur = p
        obj_ancestors[child] = chain[1:]  # exclude self

    results: list[ResolvedCallRow] = []
    for row in calls:
        call_line: int | None = None
        target_object: str | None = None
        target_proc: str | None = None
        resolution_kind = "unresolved"
        confidence = "low"

        proc_row = proc_by_key.get((row.object, row.from_proc))
        if proc_row and proc_row.body_json:
            call_line = _extract_line(proc_row.body_json, row.to_name, row.call_type)

        if row.call_type == "ExCall":
            to = row.to_name
            if "." in to:
                parts = to.rsplit(".", 1)
                first, last = parts[0], parts[1]
                if first in obj_set:
                    target_object = first
                    if last in proc_map.get(first, set()):
                        target_proc = last
                        resolution_kind = "static"
                        confidence = "high"
                    else:
                        # Check PB class methods via objects.ancestor chain
                        pb_class = _resolve_pb_class_from_ancestor(first, obj_tbl)
                        if pb_class and last.lower() in PB_CLASS_METHODS.get(pb_class.lower(), frozenset()):
                            resolution_kind = "builtin"
                            confidence = "medium"
                        else:
                            resolution_kind = "static"
                            confidence = "medium"
                elif last.lower() in PB_BUILTIN_CALLS:
                    resolution_kind = "builtin"
                    confidence = "high"
                else:
                    # Try control type inference for first segment
                    resolved_via_inference = False
                    if var_types:
                        for (obj, proc, vname), vtype in var_types.items():
                            if obj == row.object and vname == first:
                                type_chain = [vtype.lower()]
                                cur = vtype
                                visited_t = {cur}
                                while cur in inherits:
                                    p = inherits[cur]
                                    if p in visited_t:
                                        break
                                    visited_t.add(p)
                                    type_chain.append(p.lower())
                                    cur = p
                                pb_type = _resolve_pb_class_from_ancestor(vtype, obj_tbl)
                                if pb_type:
                                    type_chain.append(pb_type.lower())
                                for tc in type_chain:
                                    if last.lower() in PB_CLASS_METHODS.get(tc, frozenset()):
                                        target_object = first
                                        resolution_kind = "builtin"
                                        confidence = "medium"
                                        resolved_via_inference = True
                                        break
                            if resolved_via_inference:
                                break
                    if not resolved_via_inference:
                        resolution_kind = "unresolved"
                        confidence = "low"
            else:
                if to.lower() in PB_BUILTIN_CALLS:
                    resolution_kind = "builtin"
                    confidence = "high"
                else:
                    target_object, target_proc, resolution_kind, confidence = _resolve_virtual(
                        to, row.object, proc_map, inherits, global_procs,
                    )
                    # PB class method fallback: check caller's own PB class
                    # via objects.ancestor chain, then user-defined ancestors.
                    if resolution_kind == "unresolved":
                        pb_class = _resolve_pb_class_from_ancestor(row.object, obj_tbl)
                        if pb_class and to.lower() in PB_CLASS_METHODS.get(pb_class.lower(), frozenset()):
                            resolution_kind = "builtin"
                            confidence = "high"
                        else:
                            for ancestor in obj_ancestors.get(row.object, []):
                                pb_anc = _resolve_pb_class_from_ancestor(ancestor, obj_tbl)
                                if pb_anc and to.lower() in PB_CLASS_METHODS.get(pb_anc.lower(), frozenset()):
                                    resolution_kind = "builtin"
                                    confidence = "high"
                                    break
                    # Local variable type fallback: check if method exists
                    # on any typed local variable in the current procedure.
                    # Walk the type's own inheritance chain for user types.
                    if resolution_kind == "unresolved" and var_types:
                        for (obj, proc, vname), vtype in var_types.items():
                            if obj == row.object and (proc == row.from_proc or proc == ""):
                                # Check the type itself and its ancestors
                                type_chain = [vtype.lower()]
                                cur = vtype
                                visited = {cur}
                                while cur in inherits:
                                    p = inherits[cur]
                                    if p in visited:
                                        break
                                    visited.add(p)
                                    type_chain.append(p.lower())
                                    cur = p
                                # Also check PB class via objects.ancestor
                                pb_type = _resolve_pb_class_from_ancestor(vtype, obj_tbl)
                                if pb_type:
                                    type_chain.append(pb_type.lower())
                                for tc in type_chain:
                                    methods = PB_CLASS_METHODS.get(tc, frozenset())
                                    if to.lower() in methods:
                                        resolution_kind = "builtin"
                                        confidence = "medium"
                                        break
                            if resolution_kind != "unresolved":
                                break
                    # Control type inference fallback (Plan 90a): infer PB type
                    # from naming convention for unresolved bare calls.
                    if resolution_kind == "unresolved" and var_types:
                        for (obj, proc, vname), vtype in var_types.items():
                            if obj == row.object and (proc == row.from_proc or proc == ""):
                                inferred = infer_control_type(vname)
                                if inferred and to.lower() in PB_CLASS_METHODS.get(inferred, frozenset()):
                                    resolution_kind = "builtin"
                                    confidence = "low"
                                    break
                            if resolution_kind != "unresolved":
                                break
        elif row.call_type == "ExCallArg":
            if row.to_name.lower() in PB_BUILTIN_CALLS:
                resolution_kind = "builtin"
                confidence = "high"
            else:
                target_object, target_proc, resolution_kind, confidence = _resolve_virtual(
                    row.to_name, row.object, proc_map, inherits, global_procs,
                )
        elif row.call_type == "ExMethodCall":
            if row.to_name.lower() in PB_BUILTIN_CALLS:
                resolution_kind = "builtin"
                confidence = "high"
            else:
                resolution_kind = "unresolved"
                confidence = "low"
        elif row.call_type == "ExDispatch":
            resolution_kind = "unresolved"
            confidence = "low"

        return_type: str | None = None
        if resolution_kind == "builtin":
            to_lower = row.to_name.lower()
            method = to_lower.rsplit(".", 1)[1] if "." in to_lower else to_lower
            rt = _FREE_RETURN.get(method) or _METHOD_RETURN.get(method)
            if rt and rt.lower() not in ("void", "none", ""):
                return_type = rt

        results.append(ResolvedCallRow(
            file=row.file, object=row.object, from_proc=row.from_proc,
            to_name=row.to_name, call_type=row.call_type,
            call_line=call_line,
            target_object=target_object, target_proc=target_proc,
            resolution_kind=resolution_kind, confidence=confidence,
            return_type=return_type,
        ))

    return results


def extract_global_vars(
    global_vars_blocks: list[GlobalVarRow],
    global_instances: list[dict],
) -> list[GlobalVarRow]:
    """Return global variable rows (already extracted by importing)."""
    return global_vars_blocks
