cabal-version:      3.4
name:               pb-compiler
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Thomas Marsh
maintainer:         thomas.marsh2@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md
extra-source-files: ../runtime/*.sru

common common-settings
  default-language: GHC2024
  default-extensions:
    NoImplicitPrelude
    OverloadedStrings
    DuplicateRecordFields
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-patterns
    -Werror
    -O2

library
  import: common-settings
  hs-source-dirs: src
  exposed-modules:
    PB.Prelude
    PB.AST.BodyStmt
    PB.AST.DataWindow
    PB.AST.Expr
    PB.AST.Located
    PB.AST.SourceFile
    PB.AST.Type
    PB.Grammar.Body
    PB.Grammar.DataWindow
    PB.Grammar.File
    PB.Grammar.Stream
    PB.Lexing.DataWindow
    PB.Lexing.Escape
    PB.Lexing.Lexer
    PB.Lexing.Splitter
    PB.Lexing.Token
    PB.Analysis.Builtins
    PB.Analysis.CallClassify
    PB.Analysis.CfgBuild
    PB.Analysis.CatEval
    PB.Analysis.CatOp
    PB.Analysis.CpsCompile
    PB.Analysis.CpsInterp
    PB.Analysis.Dataflow
    PB.Analysis.DeadCode
    PB.Analysis.SSA
    PB.Analysis.Taint
    PB.Analysis.TypeEnv
    PB.Analysis.TypeResolve
    PB.Pipeline.Preprocess
    PB.Pipeline.Emit
    PB.Pipeline.Passes
    PB.Pipeline.Runner
    PB.Pipeline.Serialise
    PB.Pipeline.DuckDb
    PB.Pipeline.SqlParse
    PB.Pipeline.FileWalk
    PB.Runtime.StdLib
  build-depends:
    , base ^>=4.20.1.0
    , text
    , megaparsec
    , aeson >=2.0
    , bytestring  ^>=0.12
    , containers >=0.6
    , directory  ^>=1.3
    , file-embed ^>=0.0.16
    , filepath   >=1.4
    , mtl >=2.2
    , unordered-containers >=0.2
    , async >= 2.2
    , ghc-compact
    , time >= 1.9
    , process >= 1.6
    , vector >= 0.12
    , duckdb-simple >= 0.1.5.1 && < 0.2
    , duckdb-ffi    >= 1.5.0.0 && < 1.6
    , stm           >= 2.5
    , template-haskell

executable pbc
  import: common-settings
  hs-source-dirs: app
  main-is: Main.hs
  ghc-options: -rtsopts -threaded
  build-depends:
    , base ^>=4.20.1.0
    , pb-compiler
    , text
    , aeson
    , bytestring   ^>=0.12
    , directory    ^>=1.3
    , filepath     >=1.4
    , optparse-applicative ^>=0.18

test-suite pb-compiler-test
  import: common-settings
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules:
      DuckDbTest
    , StdLibTest
    , BodyParserTest
    , BodyStmtTest
    , CfgBuildTest
    , CorpusDebtTest
    , CpsCompileTest
    , CatEvalTest
    , CatOpTest
    , SSATest
    , DataflowTest
    , DeadCodeTest
    , TaintTest
    , DataWindowTest
    , CorpusInvariantTest
    , CorpusTest
    , EscapeTest
    , ExprTest
    , FileTest
    , PbApiTest
    , PipelineTest
    , RunnerTest
    , SerialiseTest
    , SplitterTest
    , SqlParseTest
    , StreamTest
    , TokenTest
    , TypeEnvTest
    , TypeResolveTest
  build-depends:
    , base ^>=4.20.1.0
    , pb-compiler
    , text
    , tasty
    , tasty-hunit
    , tasty-hedgehog
    , hedgehog       >=1.4
    , megaparsec
    , aeson
    , bytestring  ^>=0.12
    , containers   >=0.6
    , directory    ^>=1.3
    , filepath     >=1.4
    , mtl >=2.2
    , process >= 1.6
    , vector >= 0.12
    , duckdb-simple >= 0.1.5.1 && < 0.2
