"""Privacy-safe diagnostic for DDL statement-skip root cause.

Run against a real Oracle DDL dump. Prints ONLY aggregate counts and
keyword-frequency histograms -- never raw statement text, table names, or
column names -- so the output is safe to share even when the DDL file
itself contains sensitive schema/business data.

Mirrors pb.lib.ddl.parse_ddl's own statement pipeline (constraint-state
stripping, view-editioning stripping, TokenError-recovery split) but scans
each skipped statement's FULL un-truncated SQL text for known Oracle
physical/storage keywords -- parse_ddl's own skipped_previews truncates each
entry to 200 chars for display, which hides any tail clause that appears
after a long qualified name + column list (the common case for real Oracle
exports), so a keyword search against skipped_previews alone undercounts.

Usage:
    cd cli && uv run python scripts/diagnose_ddl_skips.py /path/to/real_schema.sql --dialect oracle [--default-namespace SCHEMA]
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

import sqlglot
from pb.lib.ddl import _split_statements, _strip_constraint_state, _strip_view_editioning_clause
from sqlglot import exp
from sqlglot.errors import ErrorLevel, TokenError

# Oracle physical-storage / partitioning / segment-attribute keywords known to
# trip sqlglot's grammar into an opaque exp.Command fallback for the whole
# statement (same failure class as ENABLE/USING INDEX, just a wider
# vocabulary). We only count matches -- never print the surrounding text.
_KEYWORDS = [
    "STORAGE", "TABLESPACE", "PCTFREE", "PCTUSED", "INITRANS", "MAXTRANS",
    "LOGGING", "NOLOGGING", "PARTITION BY", "SUBPARTITION", "ORGANIZATION INDEX",
    "COMPRESS", "NOCOMPRESS", "CACHE", "NOCACHE", "LOB", "VARRAY",
    "NESTED TABLE", "XMLTYPE", "GENERATED ALWAYS AS", "GENERATED BY DEFAULT",
    "IDENTITY", "SEGMENT CREATION", "PARALLEL", "NOPARALLEL", "MONITORING",
    "NOMONITORING", "PCTINCREASE", "MINEXTENTS", "MAXEXTENTS", "FREELISTS",
    "FREELIST GROUPS", "BUFFER_POOL", "FLASH_CACHE", "RESULT_CACHE",
    "ROWDEPENDENCIES", "NOROWDEPENDENCIES", "INMEMORY", "ENCRYPT",
    "SUPPLEMENTAL LOG", "USING INDEX", "REVERSE", "COMPUTE STATISTICS",
    "VISIBLE", "INVISIBLE", "ONLINE", "MODIFY", "UNUSABLE",
]

_LEADING_KEYWORD_RE = re.compile(
    r"^\s*(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE)?\s+(?:GLOBAL\s+TEMPORARY\s+)?(\w+)"
    r"|ALTER\s+(\w+)"
    r"|COMMENT\s+ON\s+(\w+)"
    r"|GRANT\b()"
    r"|DROP\s+(\w+))",
    re.IGNORECASE,
)


def _leading_label(sql: str) -> str:
    m = _LEADING_KEYWORD_RE.match(sql)
    if not m:
        return "(other/none)"
    for g in m.groups()[1:]:
        if g is not None:
            return g.upper() if g else "GRANT"
    return "(other/none)"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("ddl_file")
    ap.add_argument("--dialect", default="oracle")
    args = ap.parse_args()

    text = Path(args.ddl_file).read_text(errors="replace")
    stripped = _strip_view_editioning_clause(_strip_constraint_state(text))

    tokenize_error_count = 0
    try:
        statements = sqlglot.parse(stripped, dialect=args.dialect, error_level=ErrorLevel.WARN)
    except TokenError:
        statements = []
        for chunk in _split_statements(stripped):
            try:
                statements.extend(sqlglot.parse(chunk, dialect=args.dialect, error_level=ErrorLevel.WARN))
            except TokenError:
                tokenize_error_count += 1

    total = len(statements) + tokenize_error_count
    skipped_stmts = [s for s in statements if isinstance(s, exp.Command)]
    parsed_count = len(statements) - len(skipped_stmts)

    print(f"statements_total={total}")
    print(f"statements_parsed={parsed_count}")
    print(f"statements_skipped={len(skipped_stmts) + tokenize_error_count}")
    print(f"  of which tokenize_error={tokenize_error_count}, unparsed_command={len(skipped_stmts)}")
    print(f"skip_rate={(len(skipped_stmts) + tokenize_error_count) / max(total, 1):.1%}")
    print()

    leading_counts: Counter[str] = Counter()
    keyword_hits: Counter[str] = Counter()
    stmts_with_no_known_keyword = 0
    length_stats: list[int] = []

    for stmt in skipped_stmts:
        full_sql = stmt.sql(dialect=args.dialect)
        length_stats.append(len(full_sql))
        leading_counts[_leading_label(full_sql)] += 1

        upper_sql = full_sql.upper()
        hit_any = False
        for kw in _KEYWORDS:
            if kw in upper_sql:
                keyword_hits[kw] += 1
                hit_any = True
        if not hit_any:
            stmts_with_no_known_keyword += 1

    print("--- skipped statements by leading keyword (full text, not truncated) ---")
    for kw, n in leading_counts.most_common():
        print(f"  {kw}: {n}")

    print()
    print("--- Oracle physical/storage keyword hits within skipped statements (full text) ---")
    print("    (a statement can hit more than one keyword; counts overlap)")
    for kw, n in keyword_hits.most_common(40):
        print(f"  {kw}: {n}")

    print()
    print(f"skipped statements matching NONE of the known keywords: {stmts_with_no_known_keyword} / {len(skipped_stmts)}")

    if length_stats:
        length_stats.sort()
        n = len(length_stats)
        print()
        print("--- full statement length (chars) of skipped statements ---")
        print(f"  min={length_stats[0]} median={length_stats[n // 2]} max={length_stats[-1]}")


if __name__ == "__main__":
    main()
