"""Privacy-safe diagnostic for DDL statement-skip root cause.

Run against a real Oracle DDL dump. Prints ONLY aggregate counts and
keyword-frequency histograms -- never raw statement text, table names, or
column names -- so the output is safe to share even when the DDL file
itself contains sensitive schema/business data.

Usage:
    cd cli && uv run python scripts/diagnose_ddl_skips.py /path/to/real_schema.sql --dialect oracle [--default-namespace SCHEMA]
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

from pb.lib.ddl import parse_ddl

# Oracle physical-storage / partitioning / segment-attribute keywords known to
# trip sqlglot's grammar into an opaque exp.Command fallback for the whole
# statement (same failure class as ENABLE/USING INDEX, just a wider
# vocabulary). We only count matches -- never print the surrounding text.
_KEYWORDS = [
    "STORAGE", "TABLESPACE", "PCTFREE", "PCTUSED", "INITRANS", "MAXTRANS",
    "LOGGING", "NOLOGGING", "PARTITION BY", "SUBPARTITION", "ORGANIZATION INDEX",
    "COMPRESS", "NOCOMPRESS", "CACHE", "NOCACHE", "LOB", "VARRAY",
    "NESTED TABLE", "XMLTYPE", "GENERATED ALWAYS AS", "GENERATED BY DEFAULT",
    "IDENTITY", "SEGMENT CREATION", "DEFERRED", "IMMEDIATE", "PARALLEL",
    "NOPARALLEL", "MONITORING", "NOMONITORING", "PCTINCREASE", "MINEXTENTS",
    "MAXEXTENTS", "FREELISTS", "FREELIST GROUPS", "BUFFER_POOL", "FLASH_CACHE",
    "RESULT_CACHE", "ROWDEPENDENCIES", "NOROWDEPENDENCIES", "INMEMORY",
    "ENCRYPT", "SUPPLEMENTAL LOG", "USING INDEX", "REVERSE",
]

_CATEGORY_RE = re.compile(r"^\[([a-z ]+)\]")
_LEADING_KEYWORD_RE = re.compile(
    r"(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE)?\s+(?:GLOBAL\s+TEMPORARY\s+)?(\w+))", re.IGNORECASE
)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("ddl_file")
    ap.add_argument("--dialect", default="oracle")
    ap.add_argument("--default-namespace", default=None)
    args = ap.parse_args()

    text = Path(args.ddl_file).read_text(errors="replace")
    _catalog, stats = parse_ddl(text, dialect=args.dialect, default_namespace=args.default_namespace)

    print(f"statements_total={stats.statements_total}")
    print(f"statements_parsed={stats.statements_parsed}")
    print(f"statements_skipped={stats.statements_skipped}")
    print(f"skip_rate={stats.statements_skipped / max(stats.statements_total, 1):.1%}")
    print()

    cat_counts: Counter[str] = Counter()
    leading_kw_counts: Counter[str] = Counter()
    keyword_hits: Counter[str] = Counter()
    length_buckets: Counter[str] = Counter()

    for preview in stats.skipped_previews:
        m = _CATEGORY_RE.match(preview)
        category = m.group(1) if m else "unknown"
        cat_counts[category] += 1

        body = preview[m.end():].strip() if m else preview
        km = _LEADING_KEYWORD_RE.match(body)
        leading_kw_counts[km.group(2).upper() if km else "(other/none)"] += 1

        upper_body = body.upper()
        for kw in _KEYWORDS:
            if kw in upper_body:
                keyword_hits[kw] += 1

        was_truncated = len(body) >= 200
        length_buckets["truncated(>=200 chars)" if was_truncated else "short(<200 chars)"] += 1

    print("--- skipped_previews by category ---")
    for cat, n in cat_counts.most_common():
        print(f"  {cat}: {n}")

    print()
    print("--- skipped statements by leading CREATE/ALTER keyword ---")
    for kw, n in leading_kw_counts.most_common():
        print(f"  {kw}: {n}")

    print()
    print("--- Oracle physical/storage keyword hits within skipped statements ---")
    print("    (a statement can hit more than one keyword; counts overlap)")
    for kw, n in keyword_hits.most_common(30):
        print(f"  {kw}: {n}")

    print()
    print("--- preview length (were previews truncated at 200 chars?) ---")
    for bucket, n in length_buckets.most_common():
        print(f"  {bucket}: {n}")


if __name__ == "__main__":
    main()
