"""Privacy-safe diagnostic for DDL statement-skip root cause.

Run against a real Oracle DDL dump. Prints ONLY aggregate counts and
keyword-frequency histograms -- never raw statement text, table names, or
column names -- so the output is safe to share even when the DDL file
itself contains sensitive schema/business data.

Mirrors pb.lib.ddl.parse_ddl's own token-filter pipeline (2026-07-08:
replaced an earlier character-level regex implementation -- see that
module's docstring for why) so every diagnostic here reflects exactly what
the real parser does. Bisection works by slicing the token list directly
(no text reconstruction, no re-tokenizing) and redacts by token TYPE
(IDENTIFIER/STRING) rather than regex pattern matching on rendered text.

Also classifies each skipped statement as catalog-impacting or harmless:
`parse_ddl` only ever extracts columns/PK/FK/CHECK data from CREATE TABLE,
CREATE VIEW, and ALTER TABLE statements containing an ADD CONSTRAINT action
-- a plain CREATE INDEX or an ALTER TABLE with only MODIFY/ENABLE/DISABLE/
RENAME CONSTRAINT actions never feeds the catalog even when it parses
successfully, so its being "skipped" costs nothing. The raw statements_
skipped/statements_total ratio conflates the two; this script reports both.

Usage:
    cd cli && uv run python scripts/diagnose_ddl_skips.py /path/to/real_schema.sql --dialect oracle [--default-namespace SCHEMA]
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

from pb.lib.ddl import (
    _detect_hard_wrap_width,
    _dewrap_hard_wrapped_lines,
    _filter_ddl_tokens,
    _skip_paren,
    _split_statements,
)
from sqlglot import Dialect, exp
from sqlglot.errors import ErrorLevel, ParseError, TokenError
from sqlglot.tokenizer_core import Token, TokenType

# Keywords/phrases confirmed (via synthetic reproduction against sqlglot's
# oracle dialect, independent of any customer data) to trip the whole
# containing statement into an opaque exp.Command fallback. ddl.py's token
# filter now handles all of these -- this histogram exists to flag whether
# a still-failing statement contains something that OUGHT to be handled but
# somehow isn't (a real regression) versus something genuinely new.
_KEYWORDS = [
    "STORAGE", "TABLESPACE", "PCTFREE", "PCTUSED", "INITRANS", "MAXTRANS",
    "LOGGING", "NOLOGGING", "PARTITION BY", "SUBPARTITION", "ORGANIZATION INDEX",
    "COMPRESS", "NOCOMPRESS", "CACHE", "NOCACHE", "LOB", "VARRAY",
    "NESTED TABLE", "XMLTYPE", "GENERATED ALWAYS AS", "GENERATED BY DEFAULT",
    "IDENTITY", "SEGMENT CREATION", "PARALLEL", "NOPARALLEL", "MONITORING",
    "NOMONITORING", "PCTINCREASE", "MINEXTENTS", "MAXEXTENTS", "FREELISTS",
    "FREELIST GROUPS", "BUFFER_POOL", "FLASH_CACHE", "RESULT_CACHE",
    "ROWDEPENDENCIES", "NOROWDEPENDENCIES", "INMEMORY", "ENCRYPT",
    "SUPPLEMENTAL LOG", "USING INDEX", "REVERSE", "COMPUTE STATISTICS",
    "VISIBLE", "INVISIBLE", "ONLINE", "UNUSABLE", "DEFAULT ON NULL",
    "BITMAP", "BUILD", "REFRESH", "QUERY REWRITE", "BEQUEATH", "EDITIONABLE",
    "MODIFY", "ENABLE CONSTRAINT", "DISABLE CONSTRAINT", "RENAME CONSTRAINT",
    "ENABLE ", "DISABLE ",
]

_LEADING_KEYWORD_RE = re.compile(
    r"^\s*(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE)?(?:\s+(?:NON)?EDITIONABLE)?"
    r"(?:\s+MATERIALIZED)?\s+(?:GLOBAL\s+TEMPORARY\s+)?(\w+)"
    r"|ALTER\s+(\w+)"
    r"|COMMENT\s+ON\s+(\w+)"
    r"|GRANT\b()"
    r"|DROP\s+(\w+))",
    re.IGNORECASE,
)

_ADD_CONSTRAINT_RE = re.compile(r"\bADD\s+CONSTRAINT\b", re.IGNORECASE)
_INDEX_RE = re.compile(r"^\s*CREATE\s+(?:UNIQUE\s+|BITMAP\s+)?INDEX\b", re.IGNORECASE)


def _parse_tokens(dialect_instance: Dialect, tokens: list[Token], sql_for_errors: str) -> list[exp.Expr | None]:
    filtered = _filter_ddl_tokens(tokens)
    return dialect_instance.parser(error_level=ErrorLevel.WARN).parse(filtered, sql_for_errors)


def _top_level_comma_positions(tokens: list[Token], start: int, end: int) -> list[int]:
    """Indices of commas at paren-depth 0 within tokens[start:end)."""
    positions = []
    depth = 0
    for i in range(start, end):
        t = tokens[i]
        if t.token_type == TokenType.L_PAREN:
            depth += 1
        elif t.token_type == TokenType.R_PAREN:
            depth -= 1
        elif t.token_type == TokenType.COMMA and depth == 0:
            positions.append(i)
    return positions


def _redact_token_text(t: Token) -> str:
    """Per-token-type redaction: exact and robust (no regex pattern
    matching on rendered text) since the tokenizer already knows exactly
    which tokens are quoted identifiers vs. string literals."""
    if t.token_type == TokenType.IDENTIFIER:
        return "<ID>"
    if t.token_type in (TokenType.STRING, TokenType.NATIONAL_STRING):
        return "<STR>"
    return t.text


def _redacted_text(tokens: list[Token], start: int, end: int) -> str:
    return " ".join(_redact_token_text(t) for t in tokens[start:end])


def _tail_clause_would_fix(dialect_instance: Dialect, tokens: list[Token], sql: str) -> bool | None:
    """Truncate to the closing paren of the column/constraint list and
    re-parse. If the truncated form parses fine, the failure is caused
    entirely by an as-yet-unidentified TRAILING clause; if it still fails,
    the problem is inside the column/constraint definitions themselves.
    Content-free: reports only True/False/None. None if no top-level "("
    is found or it's unbalanced."""
    open_idx = next((i for i, t in enumerate(tokens) if t.token_type == TokenType.L_PAREN), None)
    if open_idx is None:
        return None
    close_idx = _skip_paren(tokens, open_idx) - 1
    if close_idx >= len(tokens) or tokens[close_idx].token_type != TokenType.R_PAREN:
        return None
    truncated = tokens[: close_idx + 1]
    try:
        parsed = _parse_tokens(dialect_instance, truncated, sql)
    except (ParseError, TokenError):
        return False
    return bool(parsed) and not isinstance(parsed[0], exp.Command)


def _isolate_failing_element(dialect_instance: Dialect, tokens: list[Token], sql: str) -> str | None:
    """Bisect the top-level comma-separated column/constraint definitions
    to find the first one whose inclusion breaks parsing, and return its
    REDACTED text (safe to print). Linear scan, not binary search: failure
    isn't guaranteed monotonic in element count (an earlier element could
    depend on context established by this one)."""
    open_idx = next((i for i, t in enumerate(tokens) if t.token_type == TokenType.L_PAREN), None)
    if open_idx is None:
        return None
    close_idx = _skip_paren(tokens, open_idx) - 1
    if close_idx >= len(tokens) or tokens[close_idx].token_type != TokenType.R_PAREN:
        return None
    commas = _top_level_comma_positions(tokens, open_idx + 1, close_idx)
    element_bounds = [open_idx + 1] + [c + 1 for c in commas]
    element_ends = commas + [close_idx]
    if not element_bounds:
        return None

    def parses(k: int) -> bool:
        candidate = tokens[: open_idx + 1] + tokens[element_bounds[0] : element_ends[k - 1]] + [tokens[close_idx]]
        try:
            parsed = _parse_tokens(dialect_instance, candidate, sql)
        except (ParseError, TokenError):
            return False
        return bool(parsed) and not isinstance(parsed[0], exp.Command)

    for k in range(1, len(element_bounds) + 1):
        if not parses(k):
            start = element_bounds[0] if k == 1 else element_bounds[k - 1]
            return _redacted_text(tokens, start, element_ends[k - 1])
    return None


def _find_query_start(tokens: list[Token]) -> int | None:
    """Index of the first top-level ALIAS ("AS") token -- marks where a
    CREATE VIEW/MATERIALIZED VIEW's underlying query begins. None if not
    found before a semicolon or end of input (e.g. a MATERIALIZED VIEW LOG,
    which references a base table via ON rather than a query via AS, or a
    genuinely malformed statement)."""
    depth = 0
    for i, t in enumerate(tokens):
        if t.token_type == TokenType.L_PAREN:
            depth += 1
        elif t.token_type == TokenType.R_PAREN:
            depth -= 1
        elif t.token_type == TokenType.SEMICOLON:
            return None
        elif t.token_type == TokenType.ALIAS and depth == 0:
            return i
    return None


def _isolate_view_header_break(dialect_instance: Dialect, tokens: list[Token], sql: str) -> str | None:
    """For a VIEW/MATERIALIZED VIEW-labeled statement: replace everything
    from AS onward with a trivial placeholder query, then bisect the
    header (everything before AS) by token count to find the shortest
    prefix that still fails. Every real failure found this session lived in
    the header (physical attributes, refresh clauses, editioning), never in
    the underlying SELECT, so this is a much sharper tool here than the
    comma-element bisection used for CREATE TABLE. Returns the REDACTED
    text around the breaking token (a few tokens of context on each side),
    or None if no AS was found or the header alone already parses fine
    (failure must be in the query itself -- rare).

    Two-phase scan, not a single forward pass: parses(k) is NOT monotonic in
    k here, unlike the CREATE TABLE comma-element case. A short prefix
    (e.g. just "CREATE", "CREATE OR") is trivially invalid regardless of
    where the real problem is, so a naive "first k that fails" would always
    report the very start of the statement. Phase 1 skips past that
    "too-short-to-be-a-header-at-all" zone to find the first k that DOES
    parse (a valid minimal header); phase 2 then finds where it breaks
    again from there, which is the real answer."""
    as_idx = _find_query_start(tokens)
    if as_idx is None:
        return None
    placeholder = dialect_instance.tokenize("SELECT 1")

    def parses(k: int) -> bool:
        candidate = tokens[:k] + placeholder
        try:
            parsed = _parse_tokens(dialect_instance, candidate, sql)
        except (ParseError, TokenError):
            return False
        return bool(parsed) and not isinstance(parsed[0], exp.Command)

    if parses(as_idx + 1):
        return None  # header alone is fine -- failure is in the query itself

    k = 1
    while k <= as_idx and not parses(k):
        k += 1
    if k > as_idx:
        return None  # never valid even close to the full header -- can't isolate

    for j in range(k, as_idx + 2):
        if not parses(j):
            start = max(0, j - 3)
            end = min(len(tokens), j + 2)
            return _redacted_text(tokens, start, end)
    return None


def _leading_label(sql: str) -> str:
    m = _LEADING_KEYWORD_RE.match(sql)
    if not m:
        return "(other/none)"
    for g in m.groups()[1:]:
        if g is not None:
            return g.upper() if g else "GRANT"
    return "(other/none)"


def _is_catalog_impacting(label: str, raw_sql: str) -> bool:
    """Mirrors parse_ddl's own consumption rule: only CREATE TABLE, CREATE
    VIEW, and an ALTER TABLE that contains an ADD CONSTRAINT action can ever
    contribute columns/PK/FK/CHECK data to the catalog -- so only losing one
    of THOSE actually loses catalog data. A plain CREATE INDEX or an ALTER
    TABLE with only MODIFY/ENABLE/DISABLE/RENAME CONSTRAINT actions was never
    going to contribute anything regardless of parse outcome."""
    if label == "TABLE" and _INDEX_RE.match(raw_sql):
        return False  # shouldn't happen (INDEX statements label as INDEX/UNIQUE), just in case
    if label in ("VIEW",):
        return True
    if label == "TABLE" and not raw_sql.strip().upper().startswith("ALTER"):
        return True  # CREATE TABLE
    if raw_sql.strip().upper().startswith("ALTER"):
        return bool(_ADD_CONSTRAINT_RE.search(raw_sql))
    return False  # CREATE INDEX / CREATE UNIQUE INDEX / CREATE BITMAP INDEX / other


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("ddl_file")
    ap.add_argument("--dialect", default="oracle")
    ap.add_argument("--default-namespace", default=None, help="accepted for CLI compatibility; unused (doesn't affect parse success/failure)")
    args = ap.parse_args()

    raw_text = Path(args.ddl_file).read_text(errors="replace")

    wrap_width = _detect_hard_wrap_width(raw_text)
    if wrap_width is not None:
        raw_text = _dewrap_hard_wrapped_lines(raw_text, wrap_width)
        print(f"NOTE: detected hard line-wrap at width={wrap_width}, reflowed before analysis")
        print()

    dialect_instance = Dialect.get_or_raise(args.dialect)
    raw_chunks = _split_statements(raw_text)

    total = len(raw_chunks)
    parsed_count = 0
    skipped: list[str] = []

    for chunk in raw_chunks:
        try:
            tokens = dialect_instance.tokenize(chunk)
            parsed = _parse_tokens(dialect_instance, tokens, chunk)
        except (ParseError, TokenError):
            parsed = []
        is_command = bool(parsed) and isinstance(parsed[0], exp.Command)
        if not parsed or is_command:
            skipped.append(chunk)
        else:
            parsed_count += 1

    print(f"statements_total={total}")
    print(f"statements_parsed={parsed_count}")
    print(f"statements_skipped={len(skipped)}")
    print(f"skip_rate={len(skipped) / max(total, 1):.1%}")
    print()

    leading_counts: Counter[str] = Counter()
    impact_counts: Counter[str] = Counter()
    keyword_hits: Counter[str] = Counter()
    keyword_hits_impacting: Counter[str] = Counter()
    none_count = 0
    none_count_impacting = 0
    length_stats: list[int] = []
    table_impacting: list[str] = []  # CREATE TABLE, catalog-impacting, still failing (any reason)
    view_impacting: list[str] = []  # CREATE/MATERIALIZED VIEW, catalog-impacting, still failing (any reason)

    for raw in skipped:
        length_stats.append(len(raw))
        label = _leading_label(raw)
        leading_counts[label] += 1
        impacting = _is_catalog_impacting(label, raw)
        impact_counts["catalog-impacting" if impacting else "harmless (never fed catalog)"] += 1

        upper = raw.upper()
        hit_any = False
        for kw in _KEYWORDS:
            if kw in upper:
                keyword_hits[kw] += 1
                hit_any = True
                if impacting:
                    keyword_hits_impacting[kw] += 1
        if not hit_any:
            none_count += 1
            if impacting:
                none_count_impacting += 1

        if impacting:
            if label == "TABLE" and not raw.strip().upper().startswith("ALTER"):
                table_impacting.append(raw)
            elif label == "VIEW":
                view_impacting.append(raw)

    print("--- skipped statements by leading keyword ---")
    for kw, n in leading_counts.most_common():
        print(f"  {kw}: {n}")

    print()
    print("--- catalog impact of skipped statements ---")
    print("    (only CREATE TABLE / CREATE VIEW / ALTER TABLE...ADD CONSTRAINT can ever")
    print("     contribute columns/PK/FK/CHECK data -- everything else was never captured")
    print("     regardless of whether it parses)")
    for label, n in impact_counts.most_common():
        print(f"  {label}: {n}")

    print()
    print("--- keyword hits, ALL skipped statements (raw text) ---")
    for kw, n in keyword_hits.most_common(40):
        print(f"  {kw}: {n}")
    print(f"  matching none: {none_count} / {len(skipped)}")

    print()
    print("--- keyword hits, CATALOG-IMPACTING skipped statements only ---")
    for kw, n in keyword_hits_impacting.most_common(40):
        print(f"  {kw}: {n}")
    print(f"  matching none: {none_count_impacting} / {impact_counts['catalog-impacting']}")

    if length_stats:
        length_stats.sort()
        n = len(length_stats)
        print()
        print("--- full statement length (chars) of skipped statements ---")
        print(f"  min={length_stats[0]} median={length_stats[n // 2]} max={length_stats[-1]}")

    if table_impacting:
        print()
        print("--- bisection of catalog-impacting CREATE TABLE losses (content-free) ---")
        print("    Truncates each statement to the closing paren of its column/constraint")
        print("    list and re-parses. 'trailing-clause' means an as-yet-unidentified tail")
        print("    keyword (same fixable class as everything already stripped) is the sole")
        print("    cause; 'inside column/constraint list' means the failure is NOT a tail")
        print("    clause and needs a different kind of fix.")
        outcome_counts: Counter[str] = Counter()
        redacted_patterns: Counter[str] = Counter()
        for raw in table_impacting:
            tokens = dialect_instance.tokenize(raw)
            result = _tail_clause_would_fix(dialect_instance, tokens, raw)
            if result is True:
                outcome_counts["trailing-clause (truncated form parses fine)"] += 1
            elif result is False:
                outcome_counts["inside column/constraint list (still fails when truncated)"] += 1
                element = _isolate_failing_element(dialect_instance, tokens, raw)
                if element is not None:
                    redacted_patterns[element] += 1
                else:
                    outcome_counts["  (bisection couldn't isolate a single element)"] += 1
            else:
                outcome_counts["unbalanced parens / could not bisect"] += 1
        for label, n in outcome_counts.most_common():
            print(f"  {label}: {n}")

        if redacted_patterns:
            print()
            print("--- isolated failing CREATE TABLE column/constraint definitions, REDACTED ---")
            print("    Every quoted identifier -> <ID>, every string literal -> <STR>.")
            print("    Deduplicated by exact redacted text -- safe to paste back as-is.")
            for pattern, n in redacted_patterns.most_common(20):
                print(f"  x{n}: {pattern}")

    if view_impacting:
        print()
        print("--- bisection of catalog-impacting VIEW/MATERIALIZED VIEW losses (content-free) ---")
        print("    Replaces everything from AS onward with a trivial placeholder query, then")
        print("    bisects the header by token count. Every real failure found this session")
        print("    lived in the header (physical attrs, refresh clauses, editioning), never")
        print("    in the underlying SELECT, so this is a sharp tool here.")
        view_redacted: Counter[str] = Counter()
        no_as_found = 0
        header_fine = 0
        for raw in view_impacting:
            tokens = dialect_instance.tokenize(raw)
            if _find_query_start(tokens) is None:
                no_as_found += 1
                continue
            element = _isolate_view_header_break(dialect_instance, tokens, raw)
            if element is not None:
                view_redacted[element] += 1
            else:
                header_fine += 1
        if no_as_found:
            print(f"  no AS found (e.g. MATERIALIZED VIEW LOG, references a table not a query): {no_as_found}")
        if header_fine:
            print(f"  header alone parses fine (failure must be in the query itself): {header_fine}")
        if view_redacted:
            print()
            print("--- isolated failing VIEW header regions, REDACTED ---")
            print("    Every quoted identifier -> <ID>, every string literal -> <STR>.")
            print("    Deduplicated by exact redacted text -- safe to paste back as-is.")
            for pattern, n in view_redacted.most_common(20):
                print(f"  x{n}: {pattern}")


if __name__ == "__main__":
    main()
