"""PB API data loaded from doc/pb2025r2 HTML docs.

Generated by scripts/extract_pb_api_sigs.py. Do not edit pb_api.json manually.
"""

from __future__ import annotations

import json
from pathlib import Path

_DATA_PATH = Path(__file__).parent / "pb_api.json"
_data: dict | None = None

# Free functions that share names with class methods in the extractor
# but are genuinely callable without a receiver (e.g. clipboard()).
_MANUAL_FREE_FUNCTIONS: list[str] = [
    "clipboard", "filerename", "posrev",
    "opensheet", "opensheetdocked", "opensheetwithparm",
    "opensheetwithparmasdocument",
    "openuserobject", "openuserobjectwithparm",
    "print", "syntaxfromsql", "classname",
]


def _load() -> dict:
    global _data
    if _data is None:
        _data = json.loads(_DATA_PATH.read_text())
    assert _data is not None
    return _data


def get_free_functions() -> frozenset[str]:
    """All PB free functions (globally callable, no receiver needed)."""
    base = set(_load()["free_function_names"])
    base.update(_MANUAL_FREE_FUNCTIONS)
    return frozenset(base)


def get_class_methods() -> dict[str, frozenset[str]]:
    """PB class methods keyed by lowercase class name."""
    raw = _load()["class_methods"]
    return {k: frozenset(v) for k, v in raw.items()}


def get_free_function_sigs() -> dict[str, list[dict]]:
    """Full signatures for free functions.

    Returns {func_name: [{"params": [...], "return_type": "..."}]}.
    Each entry may have multiple overloads in the list.
    """
    raw = _load()["free_functions"]
    return {k: v["signatures"] for k, v in raw.items() if v.get("signatures")}


def get_class_method_sigs() -> dict[str, dict[str, list[dict]]]:
    """Full signatures for class methods.

    Returns {class_name: {method_name: [{"params": [...], "return_type": "..."}]}}.
    """
    raw = _load()["classes"]
    result: dict[str, dict[str, list[dict]]] = {}
    for cls_name, cls_data in raw.items():
        methods = cls_data.get("methods", {})
        if methods:
            result[cls_name] = {m: info["signatures"] for m, info in methods.items() if info.get("signatures")}
    return result


def get_class_events() -> dict[str, dict[str, list[dict]]]:
    """Event signatures keyed by class name.

    Returns {class_name: {event_name: [{"params": [...], "return_type": "..."}]}}.
    """
    raw = _load()["classes"]
    result: dict[str, dict[str, list[dict]]] = {}
    for cls_name, cls_data in raw.items():
        events = cls_data.get("events", {})
        if events:
            result[cls_name] = {e: info["signatures"] for e, info in events.items() if info.get("signatures")}
    return result
